packages:
  - 'apps/*'

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  cpu-features: false
  esbuild: false
  nx: true
  protobufjs: false
  ssh2: false
  unrs-resolver: false
  vue-demi: false
