import type { MigrationInterface, QueryRunner } from 'typeorm'

export class InitialSchema1782527569927 implements MigrationInterface {
  name = 'InitialSchema1782527569927'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TYPE "public"."budget_type" AS ENUM('week', 'month')`)
    await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "household_id" uuid NOT NULL, "type" "public"."budget_type" NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "is_active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE UNIQUE INDEX "budgets_household_type_start_date_unique" ON "budgets"  ("household_id", "type", "start_date") `)
    await queryRunner.query(`CREATE INDEX "budgets_household_id_idx" ON "budgets"  ("household_id") `)
    await queryRunner.query(`CREATE TYPE "public"."subscription_type" AS ENUM('monthly', 'yearly')`)
    await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "household_id" uuid NOT NULL, "name" text NOT NULL, "user_id" uuid, "type" "public"."subscription_type" NOT NULL, "start_date" date NOT NULL, "end_date" date, "amount" numeric(12,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE INDEX "subscriptions_user_id_idx" ON "subscriptions"  ("user_id") `)
    await queryRunner.query(`CREATE INDEX "subscriptions_household_id_idx" ON "subscriptions"  ("household_id") `)
    await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" text NOT NULL, "name" text, "avatar_url" text, "google_id" text, "household_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE INDEX "users_household_id_idx" ON "users"  ("household_id") `)
    await queryRunner.query(`CREATE UNIQUE INDEX "users_google_id_unique" ON "users"  ("google_id") `)
    await queryRunner.query(`CREATE UNIQUE INDEX "users_email_unique" ON "users"  ("email") `)
    await queryRunner.query(`CREATE TABLE "income" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "income_type_id" uuid NOT NULL, "user_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_29a10f17b97568f70cee8586d58" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE INDEX "income_user_date_idx" ON "income"  ("user_id", "date") `)
    await queryRunner.query(`CREATE INDEX "income_user_id_idx" ON "income"  ("user_id") `)
    await queryRunner.query(`CREATE INDEX "income_income_type_id_idx" ON "income"  ("income_type_id") `)
    await queryRunner.query(`CREATE TABLE "income_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "household_id" uuid NOT NULL, "text" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2c7e145238dba7cbc7f62d3fc0a" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE UNIQUE INDEX "income_types_household_text_unique" ON "income_types"  ("household_id", "text") `)
    await queryRunner.query(`CREATE INDEX "income_types_household_id_idx" ON "income_types"  ("household_id") `)
    await queryRunner.query(`CREATE TABLE "households" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2b1aef2640717132e9231aac756" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE TYPE "public"."budget_category_type" AS ENUM('subscriptions', 'bills', 'credit_cards', 'goals', 'other')`)
    await queryRunner.query(`CREATE TABLE "budget_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "household_id" uuid NOT NULL, "name" text NOT NULL, "type" "public"."budget_category_type", "order" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2159c4d6372542f4629c4149045" PRIMARY KEY ("id"))`)
    await queryRunner.query(`CREATE UNIQUE INDEX "budget_categories_household_order_unique" ON "budget_categories"  ("household_id", "order") `)
    await queryRunner.query(`CREATE UNIQUE INDEX "budget_categories_household_name_unique" ON "budget_categories"  ("household_id", "name") `)
    await queryRunner.query(`CREATE INDEX "budget_categories_household_id_idx" ON "budget_categories"  ("household_id") `)
    await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_0b92e34429a147279d6c27298c8" FOREIGN KEY ("household_id") REFERENCES "households"("id") ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_eef7e019069826a93be41fe6a31" FOREIGN KEY ("household_id") REFERENCES "households"("id") ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a5a4e0571994849d6d4b8681089" FOREIGN KEY ("household_id") REFERENCES "households"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "income" ADD CONSTRAINT "FK_3a5de96b0fd3301705ade165220" FOREIGN KEY ("income_type_id") REFERENCES "income_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "income" ADD CONSTRAINT "FK_934ccd95e5557152309f111df82" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "income_types" ADD CONSTRAINT "FK_2a11755f5c9068c29bcec1477b8" FOREIGN KEY ("household_id") REFERENCES "households"("id") ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE "budget_categories" ADD CONSTRAINT "FK_97963b083750f51cb700dd0c4db" FOREIGN KEY ("household_id") REFERENCES "households"("id") ON DELETE CASCADE ON UPDATE NO ACTION`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "budget_categories" DROP CONSTRAINT "FK_97963b083750f51cb700dd0c4db"`)
    await queryRunner.query(`ALTER TABLE "income_types" DROP CONSTRAINT "FK_2a11755f5c9068c29bcec1477b8"`)
    await queryRunner.query(`ALTER TABLE "income" DROP CONSTRAINT "FK_934ccd95e5557152309f111df82"`)
    await queryRunner.query(`ALTER TABLE "income" DROP CONSTRAINT "FK_3a5de96b0fd3301705ade165220"`)
    await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a5a4e0571994849d6d4b8681089"`)
    await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`)
    await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_eef7e019069826a93be41fe6a31"`)
    await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_0b92e34429a147279d6c27298c8"`)
    await queryRunner.query(`DROP INDEX "public"."budget_categories_household_id_idx"`)
    await queryRunner.query(`DROP INDEX "public"."budget_categories_household_name_unique"`)
    await queryRunner.query(`DROP INDEX "public"."budget_categories_household_order_unique"`)
    await queryRunner.query(`DROP TABLE "budget_categories"`)
    await queryRunner.query(`DROP TYPE "public"."budget_category_type"`)
    await queryRunner.query(`DROP TABLE "households"`)
    await queryRunner.query(`DROP INDEX "public"."income_types_household_id_idx"`)
    await queryRunner.query(`DROP INDEX "public"."income_types_household_text_unique"`)
    await queryRunner.query(`DROP TABLE "income_types"`)
    await queryRunner.query(`DROP INDEX "public"."income_income_type_id_idx"`)
    await queryRunner.query(`DROP INDEX "public"."income_user_id_idx"`)
    await queryRunner.query(`DROP INDEX "public"."income_user_date_idx"`)
    await queryRunner.query(`DROP TABLE "income"`)
    await queryRunner.query(`DROP INDEX "public"."users_email_unique"`)
    await queryRunner.query(`DROP INDEX "public"."users_google_id_unique"`)
    await queryRunner.query(`DROP INDEX "public"."users_household_id_idx"`)
    await queryRunner.query(`DROP TABLE "users"`)
    await queryRunner.query(`DROP INDEX "public"."subscriptions_household_id_idx"`)
    await queryRunner.query(`DROP INDEX "public"."subscriptions_user_id_idx"`)
    await queryRunner.query(`DROP TABLE "subscriptions"`)
    await queryRunner.query(`DROP TYPE "public"."subscription_type"`)
    await queryRunner.query(`DROP INDEX "public"."budgets_household_id_idx"`)
    await queryRunner.query(`DROP INDEX "public"."budgets_household_type_start_date_unique"`)
    await queryRunner.query(`DROP TABLE "budgets"`)
    await queryRunner.query(`DROP TYPE "public"."budget_type"`)
  }
}
